#缓存配置文件
Database: 0 #设置要连接的数据库
ExistTime: 6000 #设置每个缓存的存活时间，单位秒。如果设置为-1则是不设置存活时间
RandExistTime: 300 #设置缓存的随机变化范围，单位秒。防止缓存雪崩
Network: tcp #redis连接协议
Address: redis-1:6379 #Redis数据库地址
InitAtStart: false #是否进行缓存初始化，即在项目启动时查询数据库重新写入缓存
InitialCache: 3000 #设置初始缓存数量，在服务器启动时写入多少记录，单位条