#从机模式配置文件

#在此配置应用要连接的Redis数据库地址
SlaveAddress: redis-2:6379

#是否进行从机初始化
SlaveInit: true
#如果此值设为true，那么在应用启动的时候会有如下操作：
#在[SlaveAddress]所指的Redis数据库中运行"slaveof [MasterHost]:[MasterPort]"指令

#在此配置应用要连接的主Redis数据库地址
#如上所述，这两项配置只在SlaveInit为true时会用到
MasterHost: redis #主机的Redis地址
MasterPort: 6379 #主机的Redis端口
