version: "3"
services:
  #应用集群，两主两从，映射端口80-83
  app:
    build: ..
    ports:
      - "80:8080"
    depends_on:
      - cassandra
      - redis
    volumes:
      - "./Config:/Config"
  app-1:
    build: ..
    ports:
      - "81:8080"
    depends_on:
      - app
    volumes:
      - "./Config-1:/Config"
  app-2:
    build: ..
    ports:
      - "82:8080"
    depends_on:
      - app-1
    volumes:
      - "./Config-2:/Config"

  #cassandra集群，两台，映射端口9042-9044
  #傻逼Windows挂载数据盘运行报错，浪费劳资时间
  #下面这个配置只能用linux上装的docker运行，基于windows hyper-V的不能用
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - "./Data/Cassandra:/var/lib/cassandra"
    command: 'cassandra -fR'
  cassandra-1:
    image: cassandra
    ports:
      - "9043:9042"
    depends_on: 
      - cassandra
    volumes:
      - "./Data/Cassandra-1:/var/lib/cassandra"
    command: 'cassandra -fR'
    environment:
      CASSANDRA_SEEDS: cassandra
  cassandra-2:
    image: cassandra
    ports:
      - "9044:9042"
    depends_on: 
      - cassandra-1
    volumes:
      - "./Data/Cassandra-2:/var/lib/cassandra"
    command: 'cassandra -fR'
    environment:
      CASSANDRA_SEEDS: cassandra-1
  
  #redis集群，四台，映射端口6379-6382
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-1:
    image: redis
    ports:
      - "6380:6379"
  redis-2:
    image: redis
    ports:
      - "6381:6379"
