version: "3"
services:
  #应用集群，两主两从，映射端口80-83
  user-auth:
    build: ..
    ports:
      - "80:8080"
    depends_on:
      - cassandra
      - redis
    volumes:
      - "./Config:/Config"
  user-auth-backup:
    build: ..
    ports:
      - "81:8080"
    depends_on:
      - user-auth
    volumes:
      - "./Config-1:/Config"
  user-auth-sub:
    build: ..
    ports:
      - "82:8080"
    depends_on:
      - user-auth
    volumes:
      - "./Config-2:/Config"

  #cassandra集群，三台，映射端口9042-9044
  cassandra:
    build: ./Cassandra
    ports:
      - "9042:9042"
    command: "cassandra -fR"
  cassandra-1:
    image: cassandra
    ports:
      - "9043:9042"
    depends_on:
      - cassandra
    command: "cassandra -fR"
    environment:
      CASSANDRA_SEEDS: cassandra
  cassandra-2:
    image: cassandra
    ports:
      - "9044:9042"
    depends_on:
      - cassandra-1
    command: "cassandra -fR"
    environment:
      CASSANDRA_SEEDS: cassandra-1

  #redis集群，三台，映射端口6379-6381
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-1:
    image: redis
    ports:
      - "6380:6379"
  redis-2:
    image: redis
    ports:
      - "6381:6379"
